------------Table No1------------
ALTER TABLE KhachHang
ADD CONSTRAINT KH_TTTG_FK FOREIGN KEY (MSTTTG) REFERENCES TrangThaiTG(MSTTTG);

ALTER TABLE KhachHang
ADD CONSTRAINT KH_PVC_FK FOREIGN KEY (MSPHH)  REFERENCES PhiVCHH(MSPHH);

ALTER TABLE KhachHang
ADD CONSTRAINT KH_CB FOREIGN KEY (MSCB)   REFERENCES ChuyenBay(MSCB);

------------Table No2------------
ALTER TABLE KhachHangNL
ADD CONSTRAINT NL_KH FOREIGN KEY (MSKH) REFERENCES KhachHang(MSKH);

------------Table No3------------
ALTER TABLE KhachHangTE
ADD CONSTRAINT TE_KH FOREIGN KEY (MSKH) REFERENCES KhachHang(MSKH);

------------Table No4------------
------------Table No5------------
------------Table No6------------
ALTER TABLE ChuyenBay
ADD CONSTRAINT CB_MB FOREIGN KEY (MSMB) REFERENCES MayBay(MSMB);

ALTER TABLE ChuyenBay
ADD CONSTRAINT CB_TB FOREIGN KEY (MSTB) REFERENCES TuyenBay(MSTB);

------------Table No7------------
ALTER TABLE GheKhach
ADD CONSTRAINT GK_KH FOREIGN KEY (MSKH) REFERENCES KhachHang(MSKH);

------------Table No8------------
ALTER TABLE MayBay
ADD CONSTRAINT MB_LMB FOREIGN KEY (MSLMB) REFERENCES LoaiMayBay(MSLMB);

------------Table No9------------
------------Table No10------------
ALTER TABLE GheNgoi
ADD CONSTRAINT GN_LMB FOREIGN KEY (MSLMB) REFERENCES LoaiMayBay(MSLMB);

------------Table No11------------
ALTER TABLE TuyenBay
ADD CONSTRAINT TBDI_G FOREIGN KEY (MSG_Di)  REFERENCES Ga(MSG);

ALTER TABLE TuyenBay
ADD CONSTRAINT TBDEN_G FOREIGN KEY (MSG_Den) REFERENCES Ga(MSG);

------------Table No12------------
------------Table No13------------
------------Table No14------------
ALTER TABLE GiaThucPham
ADD CONSTRAINT GTP_TP FOREIGN KEY (MSTP) REFERENCES ThucPham(MSTP);

------------Table No15------------
ALTER TABLE ChuyenBayThucPham
ADD CONSTRAINT CBTP_CB FOREIGN KEY (MSCB) REFERENCES ChuyenBay(MSCB);

ALTER TABLE ChuyenBayThucPham
ADD CONSTRAINT CBTP_TP FOREIGN KEY (MSTP) REFERENCES ThucPham(MSTP);

------------Table No16------------
------------Table No17------------
ALTER TABLE BangCap
ADD CONSTRAINT BC_NV FOREIGN KEY (MSNV) REFERENCES NhanVien(MSNV);

------------Table No18------------
ALTER TABLE PhiCong
ADD CONSTRAINT PC_NV FOREIGN KEY (MSNV) REFERENCES NhanVien(MSNV);

------------Table No19------------
ALTER TABLE TiepVien
ADD CONSTRAINT TV_NV FOREIGN KEY (MSNV) REFERENCES NhanVien(MSNV);

------------Table No20------------
------------Table No21------------
------------Table No22------------
ALTER TABLE NhanVienMD
ADD CONSTRAINT NVMD_NV FOREIGN KEY (MSNV) REFERENCES NhanVien(MSNV);

ALTER TABLE NhanVienMD
ADD CONSTRAINT NVMD_RE FOREIGN KEY (MSNV_Truong) REFERENCES NhanVienMD(MSNV);

ALTER TABLE NhanVienMD
ADD CONSTRAINT NVMD_CN FOREIGN KEY (MSCN) REFERENCES ChiNhanh(MSCN);

------------Table No23------------
ALTER TABLE NVMatDat_CaLV
ADD CONSTRAINT NVCA_NV FOREIGN KEY (MSNV)  REFERENCES NhanVien(MSNV);

ALTER TABLE NVMatDat_CaLV
ADD CONSTRAINT NVCA_CLV FOREIGN KEY (MSCLV) REFERENCES CaLamViec(MSCLV);

------------Table No24------------
ALTER TABLE VanHanh
ADD CONSTRAINT VH_NV FOREIGN KEY (MSNV) REFERENCES NhanVien(MSNV);

ALTER TABLE VanHanh
ADD CONSTRAINT VH_CB FOREIGN KEY (MSCB) REFERENCES ChuyenBay(MSCB);

------------Table No25------------
ALTER TABLE Lai
ADD CONSTRAINT L_NV FOREIGN KEY (MSNV) REFERENCES NhanVien(MSNV);

ALTER TABLE Lai
ADD CONSTRAINT L_LMB FOREIGN KEY (MSLMB) REFERENCES LoaiMayBay(MSLMB);

------------Table No26------------
ALTER TABLE KiemTra
ADD CONSTRAINT KT_NV FOREIGN KEY (MSNV) REFERENCES NhanVien(MSNV);

ALTER TABLE KiemTra
ADD CONSTRAINT KT_CB  FOREIGN KEY (MSCB) REFERENCES ChuyenBay(MSCB);

------------Table No27------------
ALTER TABLE ChuyenMonBD
ADD CONSTRAINT CMBD_NV FOREIGN KEY (MSNV) REFERENCES NhanVien(MSNV);

ALTER TABLE ChuyenMonBD
ADD CONSTRAINT CMBD_LMB FOREIGN KEY (MSLMB) REFERENCES LoaiMayBay(MSLMB);